### PR TITLE
Subscribe to multiple topic names and multiple pre-defined topic IDs.

### PR DESCRIPTION
**Pull request by MichalFoksa**
Command line options -t and -T may occur multiple times with mqtt-sn-sub.

### CODE REVIEW

**Comment by njh** [comment]
Hi @MichalFoksa,

Please could you fix the merge conflicts, so that this PR can be accepted?

Thanks,

nick.

**Comment by MichalFoksa** [comment]
Hi @njh 

Give me some time to catch up with project changes, PLS.

Michal

**Comment by MichalFoksa** [comment]
Hi Nicholas,

I cannot pass tests in Travis with this pull request. Do not know what the error mean.

Can you PLS help me with it?

Michal

**Comment by njh** [comment]
Ok, I will take a look. If there are no merge conflicts in Git, then I can fix any tests.

**Comment by MichalFoksa** [comment]
There are no conflicts.

I just dropped test to avoid simultaneous topic name and topic id subscription, while it is possible now. 

Thank you,
Michal

**Comment by njh** [comment]
I fixed the failing test in 495806b9481bccd39d6ff093c10b40edc47e51df

Hopefully Travis will go green again now

**Pull request merged**
