### PR TITLE
fixed binary message publish with all 0

### PR DESCRIPTION
**Pull request by saumilsdk**
Sending binary file using mqtt-sn-pub sends all zeroes. Credit goes to @mailych

### CODE REVIEW

**Comment by njh** [comment]
Thanks for the fix! It would be good to add a test for this too.
Would be good to double check that this doesn't result in uninitialised memory being transmitted.

**Comment by saumilsdk** [comment]
@njh I am not too sure with the test, can you please help me to add those? I have tested with the following change and able to see valid binary message but again not sure on the memory part. If you can help me in that will be great help. 

Currently as i required this fix, i have forked the code to my personal space and using it, but once you merge and add test/memory check, we'll use your github repo.

**Comment by njh** [comment]
Ok, I will try and write a test for this.

The good news is that your change hasn't broken any other expected behaviour 👍 

Result of the CI tests are here:
https://travis-ci.org/github/njh/mqtt-sn-tools/builds/741588887

**Comment by saumilsdk** [comment]
@njh Great. Can you please merge the PR so that we can use your github to build?

**Comment by njh** [comment]
I was unable to push a test to this branch, I think because you committed to master.

New PR in #45

**Pull request closed without merging**
